Fbook/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources "users"
  resources :posts do
    resources :likes
    resources :comments do
      resources :likes
    end
  end
  post 'friendships/create'
  resources 'likes'
  post 'comments/new'
  post 'comments/create'
  get 'posts/index'
  get 'posts/show'
  post 'posts/new'
  post 'posts/create'
end

Fbook/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :likeable, polymorphic: true
end

Fbook/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
   @like = Like.new(:post_id => params[:post_to_be_liked])
    if @like.save
      respond_to do |format|
        format.html {redirect_to :back, notice: "Liked!"}
        format.js
    end
  end
end

Fbook/app/helpers/like_helper.rb
module LikeHelper
end

Fbook/app/helpers/likes_helper.rb
module LikesHelper
end

Fbook/app/views/likes/_like_comments.html.erb
<span>
<%= object.likes.count %>
<%= link_to comment_likes_path(object), class: "text-light", method: :post do %>
  <% if liked?(subject = object, type = 'comment') %>
      <button class="btn btn-liked size-12"><i class="fas fa-thumbs-up"></i></button>
    <% else %>
      <button class="btn btn-neutral size-12"><i class="fas fa-thumbs-up"></i></button>
  <% end %>
<% end %>
Likes
</span>

Fbook/app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>