Fbook/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources "users"
  resources :posts do
    resources :likes
    resources :comments do
      resources :likes
    end
  end
  post 'friendships/create'
  resources 'likes'
  post 'comments/new'
  post 'comments/create'
  get 'posts/index'
  get 'posts/show'
  post 'posts/new'
  post 'posts/create'
end

Fbook/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likes, as: :likeable
  has_one_attached :image
end

Fbook/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #mount_uploader :image, ImageUploader
  #before_action :current_user.posts
  # validate :picture_size


  def index

    @posts = Post.order('created_at DESC')

  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
   @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
     @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
        if @post.update(params[:post].permit(:title, :body, :image))
            redirect_to posts_path
        else
            render 'edit'
        end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def like
    Like.create(user: current_user, like: params[:like])
    flash[:success] = "Like Counted!"
    redirect_to :back
  end



  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  # def picture_size
  #   errors.add(:image, 'should be less than 1MB') if image.size > 1.megabytes
  # end

end

Fbook/app/helpers/posts_helper.rb
module PostsHelper
end

Fbook/app/views/posts/_comment.html.erb
<% post.comments.each do |comment| %>
<tr id="comments_<%= comment.id %>">
<td><p><%= comment.user.email %></p></td>
<td><p><%= comment.content %></p></td>

<% if current_user == comment.user %>
<td><%= link_to "Delete Comment", [comment.post, comment], method:
:delete %></td>
<td><%= link_to "Edit Comment",
edit_post_comment_path(comment.post,comment) %></td>
<% end %>
</tr>
<% end %>

<%= render :partial => 'comments/form', :locals => {:post => post} %>

Fbook/app/views/posts/_form.html.erb
<%= render partial: 'comments/comment', locals: {post: post} %>

  <tr class="EP <%= post.id %>">
<%= form_for(post, :method => :put, remote: true) do |form| %>
<%#= form_with(model: post, local: true) do |form| %>


  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control", accept: 'image/jpeg,image/gif,image/png' %>
  </div><br />

  <div class="form-group">
  <%= form.submit "Save Post", class: 'btn btn-primary' %>
</div>
<% end %>
</tr>

Fbook/app/views/posts/edit.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1>Edit Post</h1>
    <%= render 'form', post: @post %>
    <div class="mt-2">
      <%#= link_to 'Show', @post, class: 'btn btn-info mr-2' %>
      <%#= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mr-2' %>
      <%= link_to 'Back', posts_path, class: 'btn btn-info mr-2' %>
    </div>
  </div>
</div>

Fbook/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<hr>
<% @posts.each do |post| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= post.user.full_name.capitalize  %></h5>
      <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
      <p class="card-text"><%= truncate(post.body, length: 60) %></p>
      <p class="m-1"> <%= "#{time_ago_in_words(post.created_at)} ago" %> </p>
      <h6><%= pluralize(post.comments.size, "comments") %> |
      <%= pluralize(post.likes.size, "like") %></h6>
      <%= link_to "Like",  post_path(post, like: true), method: 'post' %> |
      <%= link_to 'Comment', new_post_comment_path(post) %> |
      <%= link_to 'Edit', edit_post_path(post), class: 'card-link' %> |
      <%=link_to("Delete", post_path(post), method: :delete) %>

  </tr>
    </div>
  </div>
<% end %>

Fbook/app/views/posts/new.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path, class: 'btn btn-light mt-2' %>
  </div>
</div>

Fbook/app/views/posts/show.html.erb
<div class="container d-flex">
  <div class="row">
    <div class="col">

      <% Post.all.each do |post| %>

      <p>
      <%#= link_to(image_tag(post.image.thumb.url, alt: 'Image'), post.image.url, target: '_blank') if post.image? %>
      <%#= image_tag blog.image.variant(resize_to_limit: [100, 100]) %>
    </p>
  </div>
  </div>
</div>
<div class="card my-5">
  <div class="card-body">
    <p id="notice"><%= notice %></p>

    <h1 class="text-center"><%= post.title %></h1>
    <% if post.image.attached? %>
     < image src="<%= post.image %>">
     <% end %>
    <hr >
    <div class="my-4">
      <%= simple_format(post.body) %>
      <p class="m-1"> <%= "#{time_ago_in_words(post.created_at)} ago" %> </p>
      <h6><%= pluralize(post.comments.size, "comments") %> |
      <%= pluralize(post.likes.size, "like") %></h6>
      <p><%= link_to 'Edit', edit_post_path(post) %> |
      <%= link_to 'like', edit_post_path(post) %> |
      <%= link_to 'comment', new_post_comment_path(post) %></p>
    </div>
    <%= link_to 'Back', posts_path, class: 'btn btn-primary' %>
  </div>



<% end %>